### ISSUE TITLE
How was the baseline mentioned in the paper used？

### ISSUE THREAD

**Issue by lingjunxu1** [jhchan0805/abc#1]
This paper is absolutely fantastic! Thanks for the efforts made by you and your team! The writing in this paper is very logical, yet I still have numerous questions that require your help.

In simple terms, it would be best if you could provide or update the code for references DC05[3] and TK22[21], otherwise it would be difficult to follow your work.Because reproducing these two references according to the settings in your paper is difficult and confusing.

For example, reference DC05  should only be able to take positions on an almost fixed circle, which makes it difficult to apply to DiLiGenT because the 96 light positions in the dataset are already fixed and immutable.

Taking reference TK22 as another example, many of the statements are ambiguous, making it difficult to speculate on how the original author implemented their methods.The most impressive part of TK22 is its final step where the Smin vector is derived from the eigenvalues of a matrix. However, as more and more light rays are selected, the matrix becomes irregular and is not even a square matrix. We attempted to circumvent this issue using SVD decomposition, but its ultimate effectiveness on DiLiGenT fell short of our expectations( With a random value of 8.3, the reproduction error of TK22 was unexpectedly around 10) , which is truly a cause for concern and frustration.

We eagerly await your prompt response. It would be highly appreciated if you could update the two codes; however, if that's not possible, we would still be grateful if you could coach our doubts. Thanks so much!

**Comment by jhchan0805** [comment]
I sincerely apologize for the delayed response. First, I would like to express my gratitude for your interest in my research project. I truly appreciate your support.

Regarding the project code for the references DC05 and TK22, I have just uploaded it on the page. Feel free to reach out to me again for any issues
